# Generated by Django 5.0.6 on 2024-05-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_todo_created_at_alter_todo_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_age',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
