# Generated by Django 5.0.6 on 2024-05-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_todo_todo_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_age',
            field=models.PositiveIntegerField(blank=True, default=18, null=True),
        ),
    ]
